language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.6

install:
  - go build -o sharkey-server -v ./server
  - go build -o sharkey-client -v ./client
  - docker build -t square/sharkey-server .

script:
  # Unit tests
  - go test -v ./server
  - go test -v ./client
  # Integration tests
  - ./integration-test.sh
