language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.6
  - 1.7

install:
  - go build -o sharkey-server -v ./server
  - go build -o sharkey-client -v ./client
  - docker build -t server -f Dockerfile .
  - docker build -t client -f DockerfileClientTest .

script:
  # Unit tests
  - go test -v ./server
  - go test -v ./client
  # Integration tests
  - ./integration-test.sh
